home/__init__.py
import os
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.redis import FlaskRedis
from twilio.rest import TwilioRestClient
# from config import basedir

app = Flask(__name__)

app.config.from_object('config')

db = SQLAlchemy(app)
redis_store = FlaskRedis(app)

twilio = TwilioRestClient(app.config['TWILIO_SID'], app.config['TWILIO_TOKEN'])

# from home.api import api as api_module
from home.frontend import frontend as frontend_module

# app.register_blueprint(api_module, url_prefix='/api/v0.1')
app.register_blueprint(frontend_module, url_prefix=None)

if not app.debug and os.environ.get('HEROKU') is None:
    import logging
    from logging.handlers import RotatingFileHandler
    file_handler = RotatingFileHandler('tmp/homepage.log', 'a', 1*1024*1024, 10)
    file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
    app.logger.setLevel(logging.INFO)
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)
    app.logger.info('Homepage server startup')

if os.environ.get('HEROKU') is not None:
    import logging
    stream_handler = logging.StreamHandler()
    app.logger.addHandler(stream_handler)
    app.logger.setLevel(logging.INFO)
    app.logger.info('Homepage server startup')

from . import models, errors

home/frontend/__init__.py
#!venv/bin/python
from flask import Blueprint

frontend = Blueprint('frontend', __name__)

from . import views

home/frontend/views.py
from flask import render_template, flash, redirect, send_file, url_for, jsonify, safe_join
from home import app, redis_store, twilio
from home.frontend import frontend

FINISH_COUNT = 60

@frontend.route('/slaptext/<phone_num_str>', methods=['POST'])
def send_sms_slap(phone_num_str):
    body='\xF0\x9F\x98\xA7\xF0\x9F\x91\x8B'
    message = twilio.messages.create(to="+1"+phone_num_str,
                                     from_="+15412348051",
                                     body=body)
    return jsonify({"message": "sent slap"}), 201

@frontend.route('/runner/<runner_name>', methods=['POST'])
def update_runner(runner_name):
    state = redis_store.get('state')
    if state == 'pre_race':
        redis_store.set(runner_name, 0)
        redis_store.sadd('runners', runner_name)
    elif state == 'racing':
        print "racing"
        if redis_store.sismember('runners', runner_name)==1:
            print("sismember")
            count = redis_store.get(runner_name)
            print(count)
            if int(count) < FINISH_COUNT:
                print("incrementing")
                redis_store.incr(runner_name)
    return jsonify({runner_name: redis_store.get(runner_name)})

@frontend.route('/slapdash', methods=['GET', 'POST'])
def show_slapdash():
    redis_store.delete('runners')
    redis_store.set('state', 'pre_race')
    return render_template('slapdash.html')

@frontend.route('/slapdash/init', methods=['GET','POST'])
def init_slapdash():
    redis_store.delete('runners')
    redis_store.set('state', 'pre_race')
    return jsonify({'message': 'building field'})

@frontend.route('/slapdash/start', methods=['POST'])
def start_race():
    redis_store.set('state', 'racing')
    return jsonify({'message': 'starting'})

@frontend.route('/slapdash/update', methods=['GET'])
def update_slapdash():
    runners = []
    for member in redis_store.smembers('runners'):
        runners.append({'name':member, 'pos': redis_store.get(member)})
    return jsonify({'state': redis_store.get('state'), 'runners':runners})

@frontend.route('/test_api', methods=['GET'])
def test_api():
    return jsonify({"message": "hello!"})

@frontend.route('/test_post', methods=['POST'])
def test_post():
    return jsonify({"message": "posted!"}), 201

@frontend.route('/', methods=['GET'])
@frontend.route('/index', methods=['GET'])
def index():
    return render_template('index.html',
                            title='Home')

@frontend.route('/resume')
def get_resume():
    return render_template('resume.html',
                            title='Resume')

@frontend.route('/download/<path:filename>')
def download(filename):
    path = safe_join('static','download', filename)
    flash("Downloading " + path)
    return send_file(path)

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% if title  %}
    <title> {{ title }} </title>
    {% else %}
    <title> Neil Lakin </title>
    {% endif %}
    <link href="/static/css/bootstrap-slate.min.css" rel="stylesheet" media="screen">
    <link href="/static/css/bootstrap-slate.css" rel="stylesheet" media="screen">
    <link href="/static/css/bootstrap-social.css" rel="stylesheet" media="screen">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet" media="screen">
    <!--<link href="/static/css/bootstrap-responsive.min.css" rel="stylesheet">-->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/moment.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% include "google_analytics.html" %}

  </head>
  <body>
    <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Neil Lakin</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('frontend.index') }}">Home<span class="sr-only">(current)</span></a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="row">
      <div class="span12">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  </body>
</head>
</html>

home/templates/flash.html
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
{% for category, message in messages %}
  {% if category=='error' %}
  <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ message }}
  </div>
  {% else %}
  <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ message }}
  </div>
  {% endif %}
{% endfor %}
{% endif %}
{% endwith %}

home/templates/google_analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-93168915-1', 'auto');
  ga('send', 'pageview');

</script>

home/templates/index.html
{% extends "base.html" %}
{% block content %}
{% include "flash.html" %}
<div class="container">
  <h1>Welcome to Neil's homepage.</h1>
  <p>Sometimes it's an API server for hardware. Sometimes it's a project. Right now it's a placeholder.</p>
  <p>Go check out some projects:</p>
    <ul>
      <li><a href="http://somerandom.herokuapp.com">Some Random On Twitter</a>.
        <a href="http://github.com/nrlakin/somerandom">[github]</a>
      </li>
      <li>
        CryptoBeacon, the token-signing iBeacon.
        <a href="http://github.com/nrlakin/cryptobeacon">[github]</a>
      </li>
</div>
{% endblock %}

home/templates/resume.html
{% extends "base.html" %}

{%block content %}
<p>If you don't have a pdf plugin, you can download the file <a href= {{ url_for('frontend.download', filename='NeilLakin_resume.pdf') }}>here</a>.</p>
<object data="/static/download/NeilLakin_resume.pdf" type="application/pdf" width="100%", height="800px">

{% endblock %}

home/templates/slapdash.html
{% extends "slapdash_base.html" %}

{% block content %}
{% include "flash.html" %}
<div class="container">
  <div class="row">
    <div class="col-2-sm">
      <a class="btn btn-default" role="button" href="#" onclick="sendInit(event);">get ready...</a>
      <a class="btn btn-default" role="button" href="#" onclick="sendStart(event);">go!</a>
    </div>
  </div>
</div>
{% endblock %}

home/templates/slapdash_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% if title  %}
    <title> {{ title }} </title>
    {% else %}
    <title> SlapDash </title>
    {% endif %}
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script language="javascript" type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.0/p5.js"></script>
    <script language="javascript" type="text/javascript" src="/static/js/slapdash.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</head>
</html>